{% set version = "0.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ellipsis
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ellipsis_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ellipsis/ellipsis_{{ version }}.tar.gz
  sha256: 2b528689b84047e5eaf67fe9ef1e5a8006f4f12ca6617445c1b6584e703ab341

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rlang >=0.3.0
  run:
    - r-base
    - r-rlang >=0.3.0
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('ellipsis')"           # [not win]
    - "\"%R%\" -e \"library('ellipsis')\""  # [win]

about:
  home: https://github.com/hadley/ellipsis
  license: GPL-3
  summary: 'In S3 generics, it''s useful to take ... so that methods can have additional argument.
    But this flexibility comes at a cost: misspelled arguments will be silently ignored.
    The ellipsis packages is an experiment that allows a generic to warn if any arguments
    passed in ... are not used.'
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: ellipsis
# Version: 0.1.0
# Title: Tools for Working with ...
# Description: In S3 generics, it's useful to take ... so that methods can have additional argument. But this flexibility comes at a cost: misspelled arguments will be silently ignored. The ellipsis packages is an experiment that allows a generic to warn if any arguments passed in ... are not used.
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", role = c("aut", "cre")), person("RStudio", role = "cph") )
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# URL: https://github.com/hadley/ellipsis
# BugReports: https://github.com/hadley/ellipsis/issues
# Depends: R (>= 3.1)
# Suggests: covr, testthat
# NeedsCompilation: yes
# Packaged: 2019-02-18 23:26:43 UTC; hadley
# Author: Hadley Wickham [aut, cre], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-02-19 05:30:03 UTC
